### ISSUE TITLE
Will this extension be deprecated?

### ISSUE THREAD

**Issue by F3L1X79** [BrightcoveOS/PHP-MAPI-Wrapper#38]
Sorry for asking this here, but will this extension become incompatible with the breaking changes of June, 30 2017 due to the arrival of the new brightcove CMS API? 
https://support.brightcove.com/en/service-changes

Thank you for the answer.

**Comment by tamasd** [comment]
This library supports the old Brightcove API, that is deprecated. Please use the new APIs: https://github.com/brightcove/PHP-API-Wrapper
